# Generated by Django 5.1.2 on 2024-10-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='job',
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
